### ISSUE TITLE
Creation of namespaced links with relative URL

### ISSUE THREAD

**Issue by randomor** [stdword/logseq13-shorten-my-links#1]
Just discovered this from the forum, do we have a way to support relative URLs when **creating** namespaced page references? Is this possible with logseq plugin api?

Like when you type [[./Ideas]] from [[CoolProject]], it will automatically expand to [[Cool Project/Ideas]]?

I’ve found I often need to do this, as there are usually multiple projects that I need to create sub pages for.

**Comment by stdword** [comment]
Hello!
This plugin is totally not suited for this.
But you can use another one: `🏛 Full House Templates` [plugin](https://github.com/stdword/logseq13-full-house-plugin#readme)

## Steps
1. Create special template:
   ```
   - template:: P
       - `[c.page.name + '/' + c.args.$1]`
   ```
2. Use it to create links to sub-pages:
   ```
   {{renderer :template, P, sub page}}
   ```
   
   <img width="350px" src="https://github.com/stdword/logseq13-shorten-my-links/assets/1984175/3cd26c62-bc32-4b17-8047-88ad4621bac6"/>
3. Use `:commands` in `config.edn` to create a shortcut with carriage positioning:
   ```
   :commands [
     ["Sub Page", [[:editor/input "{{renderer :template, P, }}" {:backward-pos 2}]] ]
   ]
   ```
4. Use `/`-command to create sub pages **fastly**:
   
   <img width="450px" src="https://github.com/stdword/logseq13-shorten-my-links/assets/1984175/8b493021-add0-4f26-8e30-38f2a3a2fb4f"/>
5. Enjoy and give a star to both plugins  🤗 ❤️

**Comment by randomor** [comment]
Thanks for the detailed information. 🙏The plugin is close but what a missed opportunity, I think logseq could make the creation of relative references so much easier if I can just type `[[./subpage]]`. Is this possible with the plugin api or something one has to submit a feature request to the logseq core?

**Comment by stdword** [comment]
1. Feature request to Logseq is always the part of solution. Logseq team should accept that feature. But this is a possible way.
2. Plugin API directly didn't offer a way to modify rendering of links. But this can be achieved with some repeating parsing of current block or via slash command.

Give it a chance for my solution. It is literally not so different in terms of pressing keys:
`/pa<Enter><Sub page name>` has the same key pressing length as `[[./<Sub page name>` — 4 keys pressing and the name.

**Comment by randomor** [comment]
I'll give this a try. The keystrokes maybe the same but the cognitive distance is vast. I'm used to think in relative urls and remembering an additional shortcut is ok but just not so natural to me. Thanks for being so helpful! I'll close this issue for now.

**Comment by stdword** [comment]
Hey, @randomor! Check out something very similar to your request:
https://github.com/stdword/logseq13-shorten-my-links#2-to-have-a-very-fast-way-of-creating-or-referencing-sub-pages

**Comment by randomor** [comment]
@stdword wait did you create that? Fresh out of the oven. That's awesome. I'll play with it and let you know if I have any other ideas.
